apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: sample-mariadb-backup
  namespace: demo
spec:
  runtimeSettings:
    pod:
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      serviceAccountAnnotations: 
        iam.gke.io/gcp-service-account: "gsa-test@appscode-testing.iam.gserviceaccount.com"
  schedule: "*/5 * * * *"
  repository:
    name: gcs-repo
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: sample-mariadb
  retentionPolicy:
    name: keep-last-5
    keepLast: 5
    prune: true
