apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: sample-mariadb-restore
  namespace: demo
spec:
  runtimeSettings:
    pod:
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      serviceAccountAnnotations: 
        iam.gke.io/gcp-service-account: "gsa-test@appscode-testing.iam.gserviceaccount.com"
  repository:
    name: gcs-repo
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: sample-mariadb
  rules:
  - snapshots: [latest]
